### ISSUE TITLE
Add Review Status

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/transcription-review-backend#21]
@nassersaazi 
Proposal: Reviews should have statuses as the source of truth for a claimed transcript

Getting the review status from reading the `createdAt`(#20), `submittedAt`, or `mergedAt` would add unneeded logical comparisons.

Propose `enums` for the status field.
suggestion: 
- `active`
- `submitted`
- `merged`
- `expired`
- `closed`? @adamjonas I assume at some point we would want users to be able to close a transcript (i.e choose to not work on it anymore, the associated transcript should be `requeued` similar to expired). This field will suffice to capture that. Maybe in a future milestone

Note: Transcripts still keep their statuses i.e `queued`, `unqueued`, and `requeued`

**Comment by adamjonas** [comment]
I think you could accomplish all of what you want with a closed_at field. 

I like having timestamps over enums because it's easier to audit changes. A status field doesn't seem necessary if you build the proper functions to compare timestamps and infer the meanings. 

Created_at with no other timestamps means open and active

Created_at plus 24 hours and no other timestamps is an inactive review 

Submitted at with no merged at is an inactive transcript waiting review on BTC transcripts 

...and the like 

I could see adding closed at if someone wants to prematurely close a review before the expiration period. The rest I believe can be done with functions.

**Comment by Extheoisah** [comment]
@Emmanuel-Develops any update on this issue? I believe you handled a part of it in the cron job PR?
